services:

  weather_app:
    image: rafalon84/weather_app_image:v.1.0
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks: 
      - weather_net

  nginx-lb:
    image: rafalon84/nginx_lb_image:v.1.0
    ports:
      - "80:80"
    depends_on:
      - weather_app
    networks:
      - weather_net

  telegraf-nginx:
    image: rafalon84/telegraf_nginx_image:v.1.0
    user: root
    entrypoint: "telegraf"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - telegraf_volume:/etc/telegraf:ro
    depends_on:
      - nginx-lb
    networks:
      - weather_net
  
  prometheus-nginx:
    image: rafalon84/prometheus_nginx_image:v.1.0
    ports:
      - "9090:9090"
    volumes:
      - prometheus_volume:/etc/prometheus
    depends_on:
      - telegraf-nginx
    networks:
      - weather_net

  grafana-metrics:
    image: rafalon84/grafana_metrics_image:v.1.0
    deploy:
      restart_policy: 
        condition: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - prometheus-nginx
    networks:
      - weather_net

volumes:
  telegraf_volume:
    driver: local
  prometheus_volume:
    driver: local

networks:
  weather_net:
    driver: overlay