apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: DS_PROMETHEUS
    access: proxy
    url: http://prometheus-nginx:9090
    isDefault: true
    jsonData:
      timeInterval: "5s"
