{
 "title": "TELEGRAF CONTAINER OVERVIEW",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DATASOURCE", "query": "prometheus" },
   {
    "name": "host",
    "label": "HOST",
    "query": {
     "query": "label_values(docker_container_status_uptime_ns, host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HOST TOTAL MEM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_memory_total{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "HOST TOTAL CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_n_cpus{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "TOTAL DOCKER IMAGES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_n_images{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "TOTAL LISTENER EVENTS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_n_listener_events{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "CONTAINER LIST",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "docker_container_status_uptime_ns{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Total Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_n_containers{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Paused",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_n_containers_paused{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Stopped",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_n_containers_stopped{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_n_containers_running{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "mem_usage_percent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_usage_percent{host=\"$host\"}",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "net_rx_bytes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(docker_container_net_rx_bytes{host=\"$host\"}[5m])",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "net_tx_bytes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_net_tx_bytes{host=\"$host\"}[5m]) * -1",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "cpu_usage_percent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{host=\"$host\"}",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "MEM CONTAINER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "mem_usage_percent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "docker_container_mem_usage_percent{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "container_mem_usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "docker_container_mem_usage{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "mem_cache",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "docker_container_mem_cache{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "mem_rss",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "docker_container_mem_rss{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "mem_active_file",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "docker_container_mem_active_file{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "container_mem_limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "docker_container_mem_limit{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "mem_rss_huge",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "docker_container_mem_rss_huge{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "NET CONTAINER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "net_rx_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(docker_container_net_rx_bytes{host=\"$host\"}[5m])",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "net_rx_dropped",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(docker_container_net_rx_dropped{host=\"$host\"}[5m])",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "net_rx_errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(docker_container_net_rx_errors{host=\"$host\"}[5m])",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "net_tx_bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(docker_container_net_tx_bytes{host=\"$host\"}[5m]) * -1",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "net_tx_dropped",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(docker_container_net_tx_dropped{host=\"$host\"}[5m]) * -1",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "net_tx_errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(docker_container_net_tx_errors{host=\"$host\"}[5m]) * -1",
       "legendFormat": "{{ container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "BLKIO SERVICE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "blkio_io_service_bytes_recursive_async",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "docker_container_blkio_io_service_bytes_recursive_async{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "blkio_io_service_bytes_recursive_discard",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "docker_container_blkio_io_service_bytes_recursive_discard{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "blkio_io_service_bytes_recursive_read",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "docker_container_blkio_io_service_bytes_recursive_read{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "blkio_io_service_bytes_recursive_sync",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "docker_container_blkio_io_service_bytes_recursive_sync{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "blkio_io_service_bytes_recursive_total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "docker_container_blkio_io_service_bytes_recursive_total{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "blkio_io_service_bytes_recursive_write",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "docker_container_blkio_io_service_bytes_recursive_write{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "BLKIO SERVICED",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "blkio_io_serviced_recursive_async",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "docker_container_blkio_io_serviced_recursive_async{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "blkio_io_serviced_recursive_discard",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "docker_container_blkio_io_serviced_recursive_discard{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "blkio_io_serviced_recursive_read",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "docker_container_blkio_io_serviced_recursive_read{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "blkio_io_serviced_recursive_write",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "docker_container_blkio_io_serviced_recursive_write{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "blkio_io_serviced_recursive_total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "docker_container_blkio_io_serviced_recursive_total{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "blkio_io_serviced_recursive_sync",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "docker_container_blkio_io_serviced_recursive_sync{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU CONTAINER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu_usage_percent",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "docker_container_cpu_usage_percent{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "cpu_throttling_throttled_time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "docker_container_cpu_throttling_throttled_time{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "cpu_throttling_periods",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "docker_container_cpu_throttling_periods{host=\"$host\"}",
       "legendFormat": "{{ container_name }}"
      }
     ]
    }
   ]
  }
 ]
}