{
 "title": "TELEGRAF CONTAINER STATS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DATASOURCE", "query": "prometheus" },
   {
    "name": "host",
    "label": "HOST",
    "query": {
     "query": "label_values(docker_container_status_uptime_ns, host)"
    }
   },
   {
    "name": "container",
    "label": "CONTAINER",
    "query": {
     "query": "label_values(docker_container_status_uptime_ns{host=\"$host\"}, container_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "cpu_usage_percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{host=\"$host\", container_name=\"$container\"}",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "CONTAINER CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{host=\"$host\", container_name=\"$container\"}"
    }
   ]
  },
  {
   "title": "CONTAINER  MEM %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((docker_container_mem_usage{host=\"$host\", container_name=\"$container\"}) * 100 ) / docker_container_mem_limit{host=\"$host\", container_name=\"$container\"}"
    }
   ]
  },
  {
   "title": "HOST TOTAL CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_n_cpus{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "HOST TOTAL MEM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_memory_total{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "CONTAINER UPTIME",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - docker_container_status_uptime_ns{host=\"$host\", container_name= \"$container\", container_status=\"running\"} * -1"
    }
   ]
  },
  {
   "title": "mem_usage_percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_active_file{host=\"$host\", container_name=\"$container\"}",
     "legendFormat": "active_file"
    },
    {
     "expr": "docker_container_mem_active_anon{host=\"$host\", container_name=\"$container\"}",
     "legendFormat": "active_anon"
    },
    {
     "expr": "docker_container_mem_cache{host=\"$host\", container_name=\"$container\"}",
     "legendFormat": "mem_cache"
    },
    {
     "expr": "docker_container_mem_max_usage{host=\"$host\", container_name=\"$container\"}",
     "legendFormat": "max_usage"
    },
    {
     "expr": "docker_container_mem_rss{host=\"$host\", container_name=\"$container\"}",
     "legendFormat": "mem_rss"
    },
    {
     "expr": "docker_container_mem_usage{host=\"$host\", container_name=\"$container\"}",
     "legendFormat": "mem_usage"
    },
    {
     "expr": "docker_container_mem_limit{host=\"$host\", container_name=\"$container\"}",
     "legendFormat": "mem_limit"
    }
   ]
  },
  {
   "title": "net_rx_bytes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(docker_container_net_rx_bytes{host=\"$host\", container_name=\"$container\"}[5m])",
     "legendFormat": "rx_bytes"
    },
    {
     "expr": "rate(docker_container_net_rx_dropped{host=\"$host\", container_name=\"$container\"}[5m])",
     "legendFormat": "rx_dropped"
    },
    {
     "expr": "rate(docker_container_net_rx_errors{host=\"$host\", container_name=\"$container\"}[5m])",
     "legendFormat": "rx_errors"
    }
   ]
  },
  {
   "title": "net_tx_bytes",
   "type": "graph",
   "gridPos": { "h": 3, "w": 11, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_net_tx_bytes{host=\"$host\", container_name=\"$container\"}[5m]) * -1",
     "legendFormat": "tx_bytes"
    },
    {
     "expr": "rate(docker_container_net_tx_dropped{host=\"$host\", container_name=\"$container\"}[5m]) * -1",
     "legendFormat": "tx_dropped"
    },
    {
     "expr": "rate(docker_container_net_tx_errors{host=\"$host\", container_name=\"$container\"}[5m]) * -1",
     "legendFormat": "tx_errors"
    }
   ]
  }
 ]
}