---
- name: Install docker on EC2 instances
  hosts: all
  become: true
  tasks:
    - name: Update apt repositories
      apt:
        update_cache: yes

    - name: Install packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add GPG key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        steate: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest

    - name: Make sure that Docker is running
      service:
        name: docker
        state: started
        enabled: true
